name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    run-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello workld"
      - name: multiliine script
        run: |
          node -v
          npm -v